name: Deploy to GitHub Pages

on:
  push:
    tags:
      -

jobs:
  build:
    uses: ./.github/workflows/build-doc.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        run: |
          mkdir -p public
          cp public/index.html ./public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
